const bookList = [
    {
        id: 18094,
        name: "Ikigai",
        description:
            "It's the Japanese word for ‘a reason to live’ or ‘a reason to jump out of bed in the morning’. \r\n\r\nIt’s the place where your needs, desires, ambitions, and satisfaction meet. A place of balance. Small wonder that finding your ikigai is closely linked to living longer.\r\n\r\nFinding your ikigai is easier than you might think. This book will help you work out what your own ikigai really is, and equip you to change your life. You have a purpose in this world: your skills, your interests, your desires and your history have made you the perfect candidate for something. All you have to do is find it.\r\n\r\nDo that, and you can make every single day of your life joyful and meaningful.\r\n______________________________\r\n\r\n‘I read it and it’s bewitched me ever since. I’m spellbound.’ \r\nChris Evans\r\n\r\n'Ikigai gently unlocks simple secrets we can all use to live long, meaningful, happy lives. Science-based studies weave beautifully into honest, straight-talking conversation you won’t be able to put down. Warm, patient, and kind, this book pulls you gently along your own journey rather than pushing you from behind.' Neil Pasricha, bestselling author of",
        slug: "ikigai?vendor=booksmandala-nepal&category=hard-cover&barcode=9781786330895&used=False",
        sold: 27,
        languages: [
            {
                id: 1,
                books_count: 31832,
                is_active: true,
                created_at: "2023-04-01T09:11:51.438619Z",
                updated_at: "2023-04-01T09:11:51.438625Z",
                name: "English",
                slug: "english",
            },
        ],
        stock: 138,
        sales_price: 880,
        barcode: "9781786330895",
        genres: [
            {
                id: 49,
                reference_id: 49,
                name: "Self Improvement and Relationships",
                parent_reference_id: null,
                slug: "self-improvement-and-relationships",
            },
            {
                id: 51,
                reference_id: 51,
                name: "Self Help",
                parent_reference_id: 49,
                slug: "self-help",
            },
            {
                id: 60,
                reference_id: 60,
                name: "History, Biography, and Social Science",
                parent_reference_id: null,
                slug: "history-biography-and-social-science",
            },
            {
                id: 65,
                reference_id: 67,
                name: "Psychology",
                parent_reference_id: 60,
                slug: "psychology",
            },
            {
                id: 103,
                reference_id: 103,
                name: "Spirituality and Philosophy",
                parent_reference_id: null,
                slug: "spirituality-and-philosophy",
            },
            {
                id: 106,
                reference_id: 106,
                name: "Philosophy",
                parent_reference_id: 103,
                slug: "philosophy",
            },
        ],
        category: {
            name: "hard cover",
            slug: "hard-cover",
        },
        authors: [
            {
                id: 4536,
                name: "Hector Garcia Puigcerver",
                slug: "hector-garcia-puigcerver",
            },
        ],
        vendor: {
            name: "Booksmandala Nepal",
            slug: "booksmandala-nepal",
        },
        images: [
            {
                category: "thumbnail",
                url: "https://books.bizmandala.com/media/books/9781786330895/image.jpeg",
            },
        ],
        is_used: false,
        is_merged_stock: true,
        discount_deals: [],
        preorder_id: null,
        preorder_quantity: null,
    },
    {
        id: 40926,
        name: "November 9",
        description:
            "Beloved #1 New York Times bestselling author of It Ends With Us and All Your Perfects returns with an unforgettable love story between a writer and his unexpected muse.Fallon meets Ben, an aspiring novelist, the day before her scheduled cross-country move. Their untimely attraction leads them to spend Fallon’s last day in Los Angeles together, and her eventful life becomes the creative inspiration Ben has always sought for his novel. Over time and amidst the various relationships and tribulations of their own separate lives, they continue to meet on the same date every year. Until one day Fallon becomes unsure if Ben has been telling her the truth or fabricating a perfect reality for the sake of the ultimate plot twist. Can Ben’s relationship with Fallon—and simultaneously his novel—be considered a love story if it ends in heartbreak?",
        slug: "november-9?vendor=booksmandala-nepal&category=paper-back&barcode=9781501110344&used=False",
        sold: 10,
        languages: [
            {
                id: 1,
                books_count: 31674,
                is_active: true,
                created_at: "2023-04-01T09:11:51.438619Z",
                updated_at: "2023-04-01T09:11:51.438625Z",
                name: "English",
                slug: "english",
            },
        ],
        stock: 422,
        sales_price: 798,
        barcode: "9781501110344",
        genres: [
            {
                id: 12,
                reference_id: 11,
                name: "Fiction and Literature",
                parent_reference_id: null,
                slug: "fiction-and-literature",
            },
            {
                id: 19,
                reference_id: 19,
                name: "Drama",
                parent_reference_id: 11,
                slug: "drama",
            },
            {
                id: 25,
                reference_id: 26,
                name: "Romance",
                parent_reference_id: 11,
                slug: "romance",
            },
            {
                id: 30,
                reference_id: 30,
                name: "Young Adult",
                parent_reference_id: 11,
                slug: "young-adult",
            },
            {
                id: 38,
                reference_id: 37,
                name: "Contemporary",
                parent_reference_id: 11,
                slug: "contemporary",
            },
        ],
        category: {
            name: "paper back",
            slug: "paper-back",
        },
        authors: [
            {
                id: 2976,
                name: "Colleen Hoover",
                slug: "colleen-hoover",
            },
        ],
        vendor: {
            name: "Booksmandala Nepal",
            slug: "booksmandala-nepal",
        },
        images: [
            {
                category: "thumbnail",
                url: "https://books.bizmandala.com/media/books/9781501110344/image.jpeg",
            },
        ],
        is_used: false,
        is_merged_stock: true,
        discount_deals: [],
        preorder_id: null,
        preorder_quantity: null,
    },
    {
        id: 39584,
        name: "The 48 laws of power",
        description:
            "Drawn from 3,000 years of the history of power, this is the definitive guide to help readers achieve for themselves what Queen Elizabeth I, Henry Kissinger, Louis XIV and Machiavelli learnt the hard way. Law 1: Never outshine the master Law 2: Never put too much trust in friends; learn how to use enemies Law 3: Conceal your intentions Law 4: Always say less than necessary. The text is bold and elegant, laid out in black and red throughout and replete with fables and unique word sculptures. The 48 laws are illustrated through the tactics, triumphs and failures of great figures from the past who have wielded - or been victimised by - power.",
        slug: "the-48-laws-of-power?vendor=booksmandala-nepal&category=paper-back&barcode=9781861972781&used=False",
        sold: 13,
        languages: [
            {
                id: 1,
                books_count: 31832,
                is_active: true,
                created_at: "2023-04-01T09:11:51.438619Z",
                updated_at: "2023-04-01T09:11:51.438625Z",
                name: "English",
                slug: "english",
            },
        ],
        stock: 53,
        sales_price: 1278,
        barcode: "9781861972781",
        genres: [
            {
                id: 49,
                reference_id: 49,
                name: "Self Improvement and Relationships",
                parent_reference_id: null,
                slug: "self-improvement-and-relationships",
            },
            {
                id: 51,
                reference_id: 51,
                name: "Self Help",
                parent_reference_id: 49,
                slug: "self-help",
            },
            {
                id: 60,
                reference_id: 60,
                name: "History, Biography, and Social Science",
                parent_reference_id: null,
                slug: "history-biography-and-social-science",
            },
            {
                id: 65,
                reference_id: 67,
                name: "Psychology",
                parent_reference_id: 60,
                slug: "psychology",
            },
            {
                id: 69,
                reference_id: 70,
                name: "History",
                parent_reference_id: 60,
                slug: "history",
            },
            {
                id: 103,
                reference_id: 103,
                name: "Spirituality and Philosophy",
                parent_reference_id: null,
                slug: "spirituality-and-philosophy",
            },
            {
                id: 106,
                reference_id: 106,
                name: "Philosophy",
                parent_reference_id: 103,
                slug: "philosophy",
            },
        ],
        category: {
            name: "paper back",
            slug: "paper-back",
        },
        authors: [
            {
                id: 545,
                name: "Robert Greene",
                slug: "robert-greene",
            },
        ],
        vendor: {
            name: "Booksmandala Nepal",
            slug: "booksmandala-nepal",
        },
        images: [
            {
                category: "thumbnail",
                url: "https://books.bizmandala.com/media/books/9781861972781/image.jpeg",
            },
        ],
        is_used: false,
        is_merged_stock: true,
        discount_deals: [],
        preorder_id: null,
        preorder_quantity: null,
    },
];

export default bookList;