const Products = [
    {
        id: 602707,
        all_offer_price: 1249,
        description: "",
        category: "T-Shirt",
        color: ["green"],
        design: "Graphic Print",
        display_image:
            "men-s-green-action-team-graphic-printed-oversized-t-shirt-602707-1690265819-1.jpg",
        flip_image: null,
        parent_category: null,
        product_sizes: [
            {
                id: 1255991,
                name: "S",
                stock_status: false,
            },
            {
                id: 1255996,
                name: "M",
                stock_status: true,
            },
            {
                id: 1256003,
                name: "L",
                stock_status: true,
            },
            {
                id: 1256007,
                name: "XL",
                stock_status: true,
            },
            {
                id: 1256010,
                name: "2XL",
                stock_status: true,
            },
            {
                id: 1256020,
                name: "3XL",
                stock_status: false,
            },
        ],
        stock_status: true,
        member_price: 639,
        mrp: 1249,
        name: "Men's Green Action Team Graphic Printed Oversized T-shirt",
        custom_name:
            "Men's Green Action Team Graphic Printed Oversized T-shirt",
        offer_type: "cotm",
        price: 699,
        ptype: "single",
        subclass: "T-Shirt",
        url: "mens-green-action-team-graphic-printed-oversized-t-shirt",
        brand: "",
        model: "",
        material: "",
        status: 1,
        color_name: null,
        tribe_text: "For TriBe Members",
        tribe_image_url: "",
        designer: "bewakoof x official teenage mutant ninja turtles",
        cat_designer: "",
        in_stock: 1,
        gender: "Men",
        experiment_id: "plp_sorting;es;v3;plp_score1",
        limited_edition: false,
        group_count: 0,
        category_info: {
            gender: "Men",
            subclass: "T-Shirt",
            id: 43,
            name: "T-Shirt",
            url: "",
        },
        child_category: {
            gender: "Men",
            subclass: "T-Shirt",
            id: 43,
            name: "T-Shirt",
            url: "",
        },
        sp: null,
        offer: "14% OFF",
        coin_statement: null,
        tags: [
            {
                type: "fit",
                label: "OVERSIZED FIT",
                bgColor: "rgba(82, 82, 82, 0.8)",
                textColor: "#fff",
            },
        ],
        tribe_header: null,
        upgraded_dimension: true,
        pattern: "Graphic Print",
        member_discount: "48% OFF",
        product_discount: "44% OFF",
        manufacturer_brand: "Bewakoof®",
        fabric_tag: {
            type: "fabric",
            label: "100% COTTON",
            bgColor: "white",
            border: "1px solid #737373",
            textColor: "#737373",
        },
    },
    {
        id: 595610,
        all_offer_price: 1799,
        description: "",
        category: "T-Shirt",
        color: ["black", "white"],
        design: "Graphic Print",
        display_image:
            "pack-of-2-men-s-black-white-graphic-printed-t-shirt-595610-1685969247-1.jpg",
        flip_image: null,
        parent_category: null,
        product_sizes: [
            {
                id: 1238827,
                name: "S",
                stock_status: true,
            },
            {
                id: 1238828,
                name: "M",
                stock_status: true,
            },
            {
                id: 1238830,
                name: "L",
                stock_status: true,
            },
            {
                id: 1238832,
                name: "XL",
                stock_status: true,
            },
            {
                id: 1238835,
                name: "2XL",
                stock_status: true,
            },
            {
                id: 1238837,
                name: "3XL",
                stock_status: true,
            },
        ],
        stock_status: true,
        member_price: 739,
        mrp: 1799,
        name: "Pack of 2 Men's Black & White Graphic Printed T-shirts",
        custom_name: "Pack of 2 Men's Black & White Graphic Printed T-shirts",
        offer_type: "price_cut",
        price: 799,
        ptype: "single",
        subclass: "T-Shirt",
        url: "pack-of-2-mens-black-white-graphic-printed-t-shirt-8",
        brand: "",
        model: "",
        material: "",
        status: 1,
        color_name: null,
        tribe_text: "For TriBe Members",
        tribe_image_url: "",
        designer: "bewakoof",
        cat_designer: "",
        in_stock: 1,
        gender: "Men",
        experiment_id: "plp_sorting;es;v3;plp_score1",
        limited_edition: false,
        group_count: 0,
        category_info: {
            gender: "Men",
            subclass: "T-Shirt",
            id: 43,
            name: "T-Shirt",
            url: "",
        },
        child_category: {
            gender: "Men",
            subclass: "T-Shirt",
            id: 43,
            name: "T-Shirt",
            url: "",
        },
        sp: null,
        offer: "14% OFF",
        coin_statement: null,
        tags: [],
        tribe_header: null,
        upgraded_dimension: true,
        pattern: "Graphic Print",
        average_rating: 4.6,
        member_discount: "58% OFF",
        product_discount: "55% OFF",
        manufacturer_brand: "Bewakoof®",
        fabric_tag: {
            type: "fabric",
            label: "100% COTTON",
            bgColor: "white",
            border: "1px solid #737373",
            textColor: "#737373",
        },
    },
    {
        id: 603326,
        all_offer_price: 1299,
        description: "",
        category: "T-Shirt",
        color: ["white"],
        design: "Graphic Print",
        display_image:
            "men-s-white-the-punisher-graphic-printed-plus-size-t-shirt-603326-1689309779-1.jpg",
        flip_image: null,
        parent_category: null,
        product_sizes: [
            {
                id: 1259018,
                name: "3XL",
                stock_status: false,
            },
            {
                id: 1259019,
                name: "4XL",
                stock_status: false,
            },
            {
                id: 1259020,
                name: "5XL",
                stock_status: true,
            },
            {
                id: 1259021,
                name: "6XL",
                stock_status: false,
            },
        ],
        stock_status: true,
        member_price: 599,
        mrp: 1299,
        name: "Men's White The Punisher Graphic Printed Plus Size T-shirt",
        custom_name:
            "Men's White The Punisher Graphic Printed Plus Size T-shirt",
        offer_type: "price_cut",
        price: 649,
        ptype: "single",
        subclass: "T-Shirt",
        url: "mens-white-the-punisher-graphic-printed-plus-size-t-shirt",
        brand: "",
        model: "",
        material: "",
        status: 1,
        color_name: null,
        tribe_text: "For TriBe Members",
        tribe_image_url: "",
        designer: "marvel x bewakoof merchandise",
        cat_designer: "",
        in_stock: 1,
        gender: "Men",
        experiment_id: "plp_sorting;es;v3;plp_score1",
        limited_edition: false,
        group_count: 0,
        category_info: {
            gender: "Men",
            subclass: "T-Shirt",
            id: 43,
            name: "T-Shirt",
            url: "",
        },
        child_category: {
            gender: "Men",
            subclass: "T-Shirt",
            id: 43,
            name: "T-Shirt",
            url: "",
        },
        sp: null,
        offer: "14% OFF",
        coin_statement: null,
        tags: [
            {
                type: "fit",
                label: "PLUS SIZE",
                bgColor: "rgba(82, 82, 82, 0.8)",
                textColor: "#fff",
            },
        ],
        tribe_header: null,
        upgraded_dimension: true,
        pattern: "Graphic Print",
        average_rating: 4.7,
        member_discount: "53% OFF",
        product_discount: "50% OFF",
        manufacturer_brand: "Bewakoof®",
        fabric_tag: {
            type: "fabric",
            label: "100% COTTON",
            bgColor: "white",
            border: "1px solid #737373",
            textColor: "#737373",
        },
    },
    {
        id: 283889,
        all_offer_price: 1099,
        description: "",
        category: "T-Shirt",
        color: ["black"],
        design: "Printed",
        display_image:
            "men-s-black-batman-outline-logo-t-shirt-283889-1655747899-1.jpg",
        flip_image: null,
        parent_category: null,
        product_sizes: [
            {
                id: 541494,
                name: "S",
                stock_status: true,
            },
            {
                id: 541495,
                name: "M",
                stock_status: true,
            },
            {
                id: 541496,
                name: "L",
                stock_status: true,
            },
            {
                id: 541497,
                name: "XL",
                stock_status: true,
            },
            {
                id: 541498,
                name: "2XL",
                stock_status: true,
            },
            {
                id: 541499,
                name: "3XL",
                stock_status: true,
            },
        ],
        stock_status: true,
        member_price: 429,
        mrp: 1099,
        name: "Men's Black Batman Outline Logo T-shirt",
        custom_name: "Men's Black Batman Outline Logo T-shirt",
        offer_type: "best_seller",
        price: 466,
        ptype: "single",
        subclass: "T-Shirt",
        url: "batman-outline-logo-half-sleeve-t-shirt-for-men",
        brand: "",
        model: "",
        material: "Cotton",
        status: 1,
        color_name: null,
        tribe_text: "For TriBe Members",
        tribe_image_url: "",
        designer: "official dc comics merchandise by bewakoof.com",
        cat_designer: "",
        in_stock: 1,
        gender: "Men",
        experiment_id: "plp_sorting;es;v3;plp_score1",
        limited_edition: false,
        group_count: 0,
        category_info: {
            gender: "Men",
            subclass: "T-Shirt",
            id: 43,
            name: "T-Shirt",
            url: "",
        },
        child_category: {
            gender: "Men",
            subclass: "T-Shirt",
            id: 43,
            name: "T-Shirt",
            url: "",
        },
        sp: null,
        offer: "14% OFF",
        coin_statement: null,
        tags: [],
        tribe_header: null,
        upgraded_dimension: true,
        pattern: "Printed",
        average_rating: 4.5,
        member_discount: "60% OFF",
        product_discount: "57% OFF",
        manufacturer_brand: "Bewakoof®",
        fabric_tag: {
            type: "fabric",
            label: "100% COTTON",
            bgColor: "white",
            border: "1px solid #737373",
            textColor: "#737373",
        },
    },
    {
        id: 276320,
        all_offer_price: 999,
        description: "",
        category: "T-Shirt",
        color: ["black"],
        design: "Printed",
        display_image:
            "mickey-trio-call-half-sleeve-t-shirt-dl-276320-1679049082-1.jpg",
        flip_image: null,
        parent_category: null,
        product_sizes: [
            {
                id: 525907,
                name: "S",
                stock_status: true,
            },
            {
                id: 525908,
                name: "M",
                stock_status: true,
            },
            {
                id: 525909,
                name: "L",
                stock_status: true,
            },
            {
                id: 525910,
                name: "XL",
                stock_status: true,
            },
            {
                id: 525911,
                name: "2XL",
                stock_status: true,
            },
            {
                id: 525912,
                name: "3XL",
                stock_status: true,
            },
        ],
        stock_status: true,
        member_price: 429,
        mrp: 999,
        name: "Men's Black Mickey Trio Call (DL) Graphic Printed T-shirt",
        custom_name:
            "Men's Black Mickey Trio Call (DL) Graphic Printed T-shirt",
        offer_type: "best_seller",
        price: 469,
        ptype: "single",
        subclass: "T-Shirt",
        url: "mickey-trio-call-half-sleeve-t-shirt-for-men",
        brand: "",
        model: "",
        material: "Cotton",
        status: 1,
        color_name: null,
        tribe_text: "For TriBe Members",
        tribe_image_url: "",
        designer: "disney x bewakoof merchandise",
        cat_designer: "",
        in_stock: 1,
        gender: "Men",
        experiment_id: "plp_sorting;es;v3;plp_score1",
        limited_edition: false,
        group_count: 0,
        category_info: {
            gender: "Men",
            subclass: "T-Shirt",
            id: 43,
            name: "T-Shirt",
            url: "",
        },
        child_category: {
            gender: "Men",
            subclass: "T-Shirt",
            id: 43,
            name: "T-Shirt",
            url: "",
        },
        sp: null,
        offer: "14% OFF",
        coin_statement: null,
        tags: [],
        tribe_header: null,
        upgraded_dimension: true,
        pattern: "",
        average_rating: 4.5,
        member_discount: "57% OFF",
        product_discount: "53% OFF",
        manufacturer_brand: "Bewakoof®",
        fabric_tag: {
            type: "fabric",
            label: "100% COTTON",
            bgColor: "white",
            border: "1px solid #737373",
            textColor: "#737373",
        },
    },
    {
        id: 591131,
        all_offer_price: 1199,
        description: "",
        category: "T-Shirt",
        color: ["men"],
        design: "Typography",
        display_image:
            "men-s-black-legends-are-born-in-typography-oversized-t-shirt-591131-1685608333-1.jpg",
        flip_image: null,
        parent_category: null,
        product_sizes: [
            {
                id: 1226110,
                name: "S",
                stock_status: true,
            },
            {
                id: 1226111,
                name: "M",
                stock_status: true,
            },
            {
                id: 1226112,
                name: "L",
                stock_status: true,
            },
            {
                id: 1226113,
                name: "XL",
                stock_status: true,
            },
            {
                id: 1226114,
                name: "2XL",
                stock_status: true,
            },
        ],
        stock_status: true,
        member_price: 639,
        mrp: 1199,
        name: "Men's Black Legends Are Born In Typography Oversized T-shirt",
        custom_name:
            "Men's Black Legends Are Born In Typography Oversized T-shirt",
        offer_type: "price_cut",
        price: 699,
        ptype: "single",
        subclass: "T-Shirt",
        url: "mens-black-legends-are-born-in-oversized-t-shirt",
        brand: "",
        model: "",
        material: "",
        status: 1,
        color_name: null,
        tribe_text: "For TriBe Members",
        tribe_image_url: "",
        designer: null,
        cat_designer: "",
        in_stock: 1,
        gender: "Men",
        experiment_id: "plp_sorting;es;v3;plp_score1",
        limited_edition: false,
        group_count: 0,
        category_info: {
            gender: "Men",
            subclass: "T-Shirt",
            id: 43,
            name: "T-Shirt",
            url: "",
        },
        child_category: {
            gender: "Men",
            subclass: "T-Shirt",
            id: 43,
            name: "T-Shirt",
            url: "",
        },
        sp: null,
        offer: "14% OFF",
        coin_statement: null,
        tags: [],
        tribe_header: null,
        upgraded_dimension: true,
        pattern: "Typography",
        custom_product: true,
        member_discount: "46% OFF",
        product_discount: "41% OFF",
        manufacturer_brand: "Bewakoof®",
        fabric_tag: {
            type: "fabric",
            label: "100% COTTON",
            bgColor: "white",
            border: "1px solid #737373",
            textColor: "#737373",
        },
    },
    {
        id: 283891,
        all_offer_price: 1299,
        description: "",
        category: "T-Shirt",
        color: ["black"],
        design: "Printed",
        display_image:
            "batman-outline-logo-full-sleeve-t-shirt-bml-black-283891-1679048952-1.jpg",
        flip_image: null,
        parent_category: null,
        product_sizes: [
            {
                id: 541506,
                name: "S",
                stock_status: true,
            },
            {
                id: 541507,
                name: "M",
                stock_status: true,
            },
            {
                id: 541508,
                name: "L",
                stock_status: true,
            },
            {
                id: 541509,
                name: "XL",
                stock_status: true,
            },
            {
                id: 541510,
                name: "2XL",
                stock_status: true,
            },
            {
                id: 541511,
                name: "3XL",
                stock_status: true,
            },
        ],
        stock_status: true,
        member_price: 519,
        mrp: 1299,
        name: "Men's Black Batman Outline Logo (BML) Printed T-shirt",
        custom_name: "Men's Black Batman Outline Logo (BML) Printed T-shirt",
        offer_type: "best_seller",
        price: 560,
        ptype: "single",
        subclass: "T-Shirt",
        url: "batman-outline-logo-full-sleeve-t-shirt-for-men",
        brand: "",
        model: "",
        material: "Cotton",
        status: 1,
        color_name: null,
        tribe_text: "For TriBe Members",
        tribe_image_url: "",
        designer: "official dc comics merchandise by bewakoof.com",
        cat_designer: "",
        in_stock: 1,
        gender: "Men",
        experiment_id: "plp_sorting;es;v3;plp_score1",
        limited_edition: false,
        group_count: 0,
        category_info: {
            gender: "Men",
            subclass: "T-Shirt",
            id: 43,
            name: "T-Shirt",
            url: "",
        },
        child_category: {
            gender: "Men",
            subclass: "T-Shirt",
            id: 43,
            name: "T-Shirt",
            url: "",
        },
        sp: null,
        offer: "14% OFF",
        coin_statement: null,
        tags: [],
        tribe_header: null,
        upgraded_dimension: true,
        pattern: "Printed",
        average_rating: 4.4,
        member_discount: "60% OFF",
        product_discount: "56% OFF",
        manufacturer_brand: "Bewakoof®",
        fabric_tag: {
            type: "fabric",
            label: "100% COTTON",
            bgColor: "white",
            border: "1px solid #737373",
            textColor: "#737373",
        },
    },
    {
        id: 231465,
        all_offer_price: 1099,
        description: "",
        category: "T-Shirt",
        color: ["white"],
        design: "Printed",
        display_image:
            "men-s-white-world-peace-t-shirt-231465-1655747902-1.jpg",
        flip_image: null,
        parent_category: null,
        product_sizes: [
            {
                id: 440093,
                name: "S",
                stock_status: true,
            },
            {
                id: 440094,
                name: "M",
                stock_status: true,
            },
            {
                id: 440095,
                name: "L",
                stock_status: true,
            },
            {
                id: 440096,
                name: "XL",
                stock_status: true,
            },
            {
                id: 440097,
                name: "2XL",
                stock_status: true,
            },
            {
                id: 440098,
                name: "3XL",
                stock_status: true,
            },
        ],
        stock_status: true,
        member_price: 409,
        mrp: 1099,
        name: "Men's White World Peace Graphic Printed T-shirt",
        custom_name: "Men's White World Peace Graphic Printed T-shirt",
        offer_type: "best_seller",
        price: 449,
        ptype: "single",
        subclass: "T-Shirt",
        url: "world-peace-white-half-sleeve-t-shirt-for-men",
        brand: "",
        model: "",
        material: "Cotton",
        status: 1,
        color_name: null,
        tribe_text: "For TriBe Members",
        tribe_image_url: "",
        designer: "bewakoof",
        cat_designer: "",
        in_stock: 1,
        gender: "Men",
        experiment_id: "plp_sorting;es;v3;plp_score1",
        limited_edition: false,
        group_count: 0,
        category_info: {
            gender: "Men",
            subclass: "T-Shirt",
            id: 43,
            name: "T-Shirt",
            url: "",
        },
        child_category: {
            gender: "Men",
            subclass: "T-Shirt",
            id: 43,
            name: "T-Shirt",
            url: "",
        },
        sp: null,
        offer: "14% OFF",
        coin_statement: null,
        tags: [],
        tribe_header: null,
        upgraded_dimension: true,
        pattern: "Printed",
        average_rating: 4.4,
        member_discount: "62% OFF",
        product_discount: "59% OFF",
        manufacturer_brand: "Bewakoof®",
        fabric_tag: {
            type: "fabric",
            label: "100% COTTON",
            bgColor: "white",
            border: "1px solid #737373",
            textColor: "#737373",
        },
    },
];

export default Products;